/**
 * Copyright 2026 Charles Lett Jr.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.bearzwebworks.beardb.db.model;

public class Customer {
    // auto generated by database
    private int customerID;

    private String CompanyName;
    private String Billing;
    private String City;
    private String State;
    private String ZIP;
    private String Country;
    private String Comments;

    public boolean matches(String searchString) {
        String name = getCompanyName().toLowerCase();
        searchString = searchString.toLowerCase();

        return name.contains(searchString);
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerID=" + customerID +
                ", CompanyName='" + CompanyName + '\'' +
                ", Billing='" + Billing + '\'' +
                ", City='" + City + '\'' +
                ", State='" + State + '\'' +
                ", ZIP='" + ZIP + '\'' +
                ", Country='" + Country + '\'' +
                ", Comments='" + Comments + '\'' +
                '}';
    }

    public int getCustomerID() {
        return customerID;
    }

    public void setCustomerID(int customerID) {
        this.customerID = customerID;
    }

    public String getCompanyName() {
        return CompanyName;
    }

    public void setCompanyName(String companyName) {
        CompanyName = companyName;
    }

    public String getBilling() {
        return Billing;
    }

    public void setBilling(String billing) {
        Billing = billing;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String city) {
        City = city;
    }

    public String getState() {
        return State;
    }

    public void setState(String state) {
        State = state;
    }

    public String getZIP() {
        return ZIP;
    }

    public void setZIP(String ZIP) {
        this.ZIP = ZIP;
    }

    public String getCountry() {
        return Country;
    }

    public void setCountry(String country) {
        Country = country;
    }

    public String getComments() {
        return Comments;
    }

    public void setComments(String comments) {
        Comments = comments;
    }
}
