/**
 * Copyright (c) 2023 Charles Lett Jr. All rights reserved.
 *
 * This code is the property of Charles Lett Jr. and may not be used or distributed without permission.
 * Unauthorized use or distribution of this code may result in legal action.
*/

package com.bearzwebworks.beardb.db.model;

public class Customer {
    // auto generated by database
    private int customerID;

    private String CompanyName;
    private String Billing;
    private String City;
    private String State;
    private String ZIP;
    private String Country;
    private String Comments;

    public boolean matches(String searchString) {
        String name = getCompanyName().toLowerCase();
        searchString = searchString.toLowerCase();

        return name.contains(searchString);
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerID=" + customerID +
                ", CompanyName='" + CompanyName + '\'' +
                ", Billing='" + Billing + '\'' +
                ", City='" + City + '\'' +
                ", State='" + State + '\'' +
                ", ZIP='" + ZIP + '\'' +
                ", Country='" + Country + '\'' +
                ", Comments='" + Comments + '\'' +
                '}';
    }

    public int getCustomerID() {
        return customerID;
    }

    public void setCustomerID(int customerID) {
        this.customerID = customerID;
    }

    public String getCompanyName() {
        return CompanyName;
    }

    public void setCompanyName(String companyName) {
        CompanyName = companyName;
    }

    public String getBilling() {
        return Billing;
    }

    public void setBilling(String billing) {
        Billing = billing;
    }

    public String getCity() {
        return City;
    }

    public void setCity(String city) {
        City = city;
    }

    public String getState() {
        return State;
    }

    public void setState(String state) {
        State = state;
    }

    public String getZIP() {
        return ZIP;
    }

    public void setZIP(String ZIP) {
        this.ZIP = ZIP;
    }

    public String getCountry() {
        return Country;
    }

    public void setCountry(String country) {
        Country = country;
    }

    public String getComments() {
        return Comments;
    }

    public void setComments(String comments) {
        Comments = comments;
    }
}
